"""
Exchange Rates Custom Metrics for Prometheus
Métriques métier spécifiques aux taux de change
"""

from prometheus_client import Counter, Gauge, Histogram


# Métriques de récupération des taux de change
EXCHANGE_RATE_FETCH_SUCCESS = Counter(
    'exchange_rate_fetch_success_total',
    'Successful exchange rate fetches from BAM API',
    ['currency_pair', 'source']
)

EXCHANGE_RATE_FETCH_ERROR = Counter(
    'exchange_rate_fetch_error_total',
    'Failed exchange rate fetches from BAM API',
    ['currency_pair', 'error_type']
)

# Valeurs actuelles des taux de change
LAST_EXCHANGE_RATE = Gauge(
    'exchange_rate_last_value',
    'Last fetched exchange rate value',
    ['currency_pair', 'rate_type']  # rate_type: achat/vente/moyen
)

# Temps de réponse de l'API BAM
BAM_API_RESPONSE_TIME = Histogram(
    'bam_api_response_seconds',
    'BAM API response time in seconds',
    ['endpoint', 'currency']
)

# Métriques de prédictions ML
PREDICTION_GENERATED = Counter(
    'prediction_generated_total',
    'Total predictions generated by ML model',
    ['currency_pair', 'model_version']
)

PREDICTION_ERROR = Counter(
    'prediction_error_total',
    'Prediction generation errors',
    ['currency_pair', 'error_type']
)

# Qualité du modèle ML
MODEL_ACCURACY_METRICS = Gauge(
    'model_accuracy_score',
    'ML model accuracy metrics',
    ['currency_pair', 'metric_type']  # metric_type: mae/mse/rmse/mape
)

# Taux de prédictions vs taux réels (écart)
PREDICTION_DEVIATION = Gauge(
    'prediction_deviation_percentage',
    'Deviation between predicted and actual rates',
    ['currency_pair']
)

# Santé du scheduler
SCHEDULER_JOB_SUCCESS = Counter(
    'scheduler_job_success_total',
    'Successful scheduler job executions',
    ['job_name']
)

SCHEDULER_JOB_ERROR = Counter(
    'scheduler_job_error_total',
    'Failed scheduler job executions',
    ['job_name', 'error_type']
)

SCHEDULER_JOB_DURATION = Histogram(
    'scheduler_job_duration_seconds',
    'Scheduler job execution duration',
    ['job_name']
)

# Nombre de taux en base de données
EXCHANGE_RATES_IN_DB = Gauge(
    'exchange_rates_stored_total',
    'Total exchange rates stored in database',
    ['currency_pair', 'rate_type']  # rate_type: actual/predicted
)
